# Configuração de Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/convite_casamento
spring.datasource.username=postgres
spring.datasource.password=1234

# Configurações do Hibernate (JPA)
# O 'update' faz o Spring criar ou atualizar as tabelas automaticamente para você
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.cache=false